### ISSUE TITLE
Metasploit in opt directory

### ISSUE THREAD

**Issue by archey** [anthraxx/arch-pkgbuilds#4]
Anthraxx, 

I know this is advised by metasploit to place the files into /opt, but this is not FHS compliant would it be possible to update it to /usr/share/$pkgname if possible?

**Comment by anthraxx** [comment]
what exactly is not FHS compliant with /opt?

also /usr/share/$pkgbuild is only meant for static data that does never change or alter.

**Comment by archey** [comment]
Well its not usually in a users path, and how is /usr/share/$pkgname only for static data as pkgs update the code changes.

**Comment by anthraxx** [comment]
well thats why the binaries are symlinked to /usr/bin. there is literally absolutely no reason it needs to be in the path.
The whole structure is a self contained application which best fits into /opt (thats pretty much its reason for existence). 

/usr/share/$pkgname is static for the one installation you have, not forever if you update the package. And in the world of metasploit you may possibly alter that structure by certain config or database foo, so its not static during one installation.

Since we agree /opt is FHS compliant, what exactly is the problem you try to solve?

**Comment by archey** [comment]
We have packages that call our path, of /usr/share/$pkgname which we will have to fix. I was trying to get around that, but its fine. We will fix our stuff, thanks for listening.

**Comment by anthraxx** [comment]
what kind of stuff does directly call /usr/share/$pkgname? do they call the msf* binaries? Those should have been exposed to something inside the PATH (f.e. symlink to /usr/bin) and be called without any absolute paths.

**Comment by archey** [comment]
Its fine, we will fix the programs that call the pah of metasploit on our side. Our users are already getting conflict issues due to the epoch on our version. We are removing it from our repo to get around this issue.

**Comment by archey** [comment]
Users of our repo will get a notification that the version in our repo is newer then community, however we are correcting it. Its just unfortunate about the downgrade notification they may see if they are on the latest version of metasploit from us.

**Comment by anthraxx** [comment]
I see, thanks for the feedback to my question :smiley_cat: 
Feel free to close this if there are no issues left
